### ISSUE TITLE
Append 'trigger icon' in any place of the page

### ISSUE THREAD

**Issue by Globulopolis** [tsi/inlineDisqussions#2]
Hi! Few hours ago I wrote a plugin for Joomla which is use your plugin. But I think what sometimes in different situation(and web page layouts) we need to add an icon to other place than the default or even to another DOM element on that page.

Can you implement this?

PS! And I found small bug in css. For #disqus_thread we need to add a white background and gray border, because div with the form have a transparent background by default.

**Comment by tsi** [comment]
Hi, thanks for your contribution to the Joomla community.

> add an icon to other place than the default

Addiing a setting for a selector to append the icons to a different element then the default would be pretty easy, the problem is their positioning, since we can't tell where they are. any suggestions regarding that?

> PS! And I found small bug in css. 

I don't see that as a bug, if you need a background you can easily add that, I prefer not making too many assumptions your design.

**Comment by Globulopolis** [comment]
"the problem is their positioning, since we can't tell where they are. any suggestions regarding that?"
Ok. At first - when we call a plugin we pass element(s) as selector for binding trigger to it. So we can attach icon just to this element. And attach a form after it. Or add additional parameter for form.
Example:
$('.article').plugin({attachFormTo: '.readmore'});
In this situation we attach icon to div with class article and add form after .readmore element(a or div or something else).

"I don't see that as a bug, if you need a background you can easily add that, I prefer not making too many assumptions your design."
Yes. It is not a bug. But look at the image
![clipboard02](https://f.cloud.github.com/assets/740757/1103448/f22e9732-18a9-11e3-8a13-acc6d0521ce5.jpg)

**Comment by tsi** [comment]
Just added a background color setting. I don't get the other issue.

**Comment by draganbabic** [comment]
Hi Tshachi, first of all thanks for a great plugin. I'd like to resurrect this issue as you may be able to help us out and contribute to our project. 

If you take a look at [this demo](http://sprawsm.com/discussions/) you'll see that we made a small jQuery widget to allow people to embed discuss to their mockups, so that they can have conversations about their designs right on top of the mockups themselves. 

Now, looking at your plugin it seems that it would fit in perfectly with ours in the sense that with yours we could enable people to add annotations to the design. 

I don't want to go into the deep specifics at this point as I just wanted to see if you would be interested to help out on this "integration". 

Thanks.

**Comment by tsi** [comment]
Hi @draganbabic thanks for your comment,
This issue is resolved already, but I invite you to open a new one, please explain what exactly you need from me.
Tsachi
